[package]
name = "scry_isa"
version = "0.1.0"
authors = ["Emad Jacob Maroun <emoun.open@gmail.com>"]
edition = "2018"

[dependencies]
duplicate="0.2"
lazy_static = "1.4"
variant_count="=1.1.0"
paste="1.0.5"

[dev-dependencies]
quickcheck="1"
quickcheck_macros = "1"
num-traits = "0.2"