test_assembly! {
	"add High+Low, =>0"
	"add Low+High, =>31"
	"add High=>Low, =>21"
	"add Low=>High, =>24"
	"add High, =>1"
	"add Low, =>11"
	"sub High+Low, =>0"
	"sub Low+High, =>31"
	"sub High=>Low, =>7"
	"sub Low=>High, =>30"
	"sub High, =>5"
	"sub Low, =>18"
	"shl High+Low, =>4"
	"shl Low+High, =>29"
	"shl High=>Low, =>5"
	"shl Low=>High, =>0"
	"shl High, =>31"
	"shr Low, =>23"
	"shr High+Low, =>13"
	"shr Low+High, =>27"
	"shr High=>Low, =>0"
	"shr Low=>High, =>20"
	"shr High, =>0"
	"shr Low, =>10"
}
